### ISSUE TITLE
Random brands.town posts

### ISSUE THREAD

**Issue by SomethingGeneric** [SomethingGeneric/Gamerbot#15]

**Comment by SomethingGeneric** [comment]
@orowith2os was this your idea?

**Comment by orowith2os** [comment]
Nah, was Fries'

**Comment by SomethingGeneric** [comment]
moving to https://github.com/SomethingGeneric/GamerbotAgain/issues/1 since it's a feature request and will require some work

**Comment by orowith2os** [comment]
maybe mark as not planned rather than completed

**Comment by SomethingGeneric** [comment]
is that a thing i can do??

**Comment by orowith2os** [comment]
> is that a thing i can do??

there should be a lil dropdown next to the close/reopen button to do that

**Comment by SomethingGeneric** [comment]
nuts

**Comment by orowith2os** [comment]
balls
