### ISSUE TITLE
link code for `linkfediverse`

### ISSUE THREAD

**Issue by SomethingGeneric** [SomethingGeneric/Gamerbot#22]
@orowith2os really just wants me to suffer :upside_down_face:

**Comment by orowith2os** [comment]
> 1. -linkfediverse @user@oro
> 2. DM Discord user with a verification code
> 3. Ask Discord user to DM Gamerbot on Mastodon at the provided @@ the verification code
> 4. profit

Is what I suggested, but might be easier to instead send the user a verification code on Mastodon (via DMs) and input the verification code on Discord.

**Comment by SomethingGeneric** [comment]
> > 1. -linkfediverse @user@oro
> > 2. DM Discord user with a verification code
> > 3. Ask Discord user to DM Gamerbot on Mastodon at the provided @@ the verification code
> > 4. profit
> 
> Is what I suggested, but might be easier to instead send the user a verification code on Mastodon (via DMs) and input the verification code on Discord.

way easier to do the reverse yea
