### ISSUE TITLE
completely empty -toot commands only send Enmpty

### ISSUE THREAD

**Issue by orowith2os** [SomethingGeneric/Gamerbot#23]
If one runs `-toot` with an image, it'll send a Mastodon post with that image and the word "Enmpty".

However, if one just runs `-toot`, with no arguments, it posts "Enmpty".

It should check for if there are no additions at all, and if none, don't send anything

**Comment by SomethingGeneric** [comment]
So you'd want to not post if no image and no text.

And post image w/ no caption if just image?

**Comment by orowith2os** [comment]
bingo
